import * as stylex from "@stylexjs/stylex";

export const analyticsStyles = stylex.create({
  page: {
    width: "min(1120px, calc(100% - 32px))",
    marginInline: "auto",
    paddingBlock: "64px 96px",
  },
  heading: {
    display: "grid",
    gridTemplateColumns: { default: "1fr auto", "@media (max-width: 720px)": "1fr" },
    alignItems: "end",
    gap: "24px",
    marginBottom: "28px",
  },
  eyebrow: {
    color: "#a991ff",
    fontSize: "12px",
    fontWeight: 800,
    letterSpacing: ".16em",
    marginBottom: "12px",
  },
  title: {
    margin: 0,
    fontSize: "clamp(38px, 5vw, 62px)",
    lineHeight: 1,
    letterSpacing: "-.055em",
  },
  intro: {
    color: "#9aa0b4",
    lineHeight: 1.6,
    maxWidth: "680px",
    marginBottom: "28px",
  },
  rangeGroup: { display: "flex", flexWrap: "wrap", gap: "8px" },
  rangeButton: {
    minHeight: "40px",
    borderRadius: "12px",
    border: "1px solid rgba(255,255,255,.12)",
    background: "rgba(255,255,255,.04)",
    color: "#f7f7fb",
    fontWeight: 800,
    paddingInline: "14px",
    cursor: "pointer",
  },
  activeRange: { background: "#f7f7fb", color: "#0a0b10" },
  summaryGrid: {
    display: "grid",
    gridTemplateColumns: { default: "repeat(4, minmax(0, 1fr))", "@media (max-width: 860px)": "repeat(2, minmax(0, 1fr))", "@media (max-width: 520px)": "1fr" },
    gap: "12px",
    marginBottom: "18px",
  },
  metric: {
    border: "1px solid rgba(255,255,255,.1)",
    background: "rgba(255,255,255,.035)",
    borderRadius: "20px",
    padding: "20px",
  },
  metricLabel: { color: "#858b9e", fontSize: "12px", fontWeight: 800, letterSpacing: ".09em" },
  metricValue: { display: "block", fontSize: "32px", letterSpacing: "-.04em", marginTop: "8px" },
  metricHelp: { color: "#70768a", fontSize: "12px", lineHeight: 1.45, marginTop: "6px" },
  grid: {
    display: "grid",
    gridTemplateColumns: { default: "minmax(0, 1.4fr) minmax(300px, .6fr)", "@media (max-width: 900px)": "1fr" },
    gap: "16px",
  },
  stack: { display: "grid", gap: "16px" },
  panel: {
    minWidth: 0,
    border: "1px solid rgba(255,255,255,.1)",
    background: "rgba(255,255,255,.035)",
    borderRadius: "22px",
    padding: "20px",
  },
  panelHeader: { display: "flex", alignItems: "baseline", justifyContent: "space-between", gap: "12px", marginBottom: "14px" },
  panelTitle: { margin: 0, fontSize: "19px" },
  subtle: { color: "#858b9e", fontSize: "13px" },
  tableWrap: { overflowX: "auto" },
  table: { width: "100%", borderCollapse: "collapse", fontSize: "14px" },
  th: { color: "#858b9e", fontSize: "11px", letterSpacing: ".08em", textAlign: "left", padding: "10px 8px", borderBottom: "1px solid rgba(255,255,255,.08)" },
  td: { padding: "11px 8px", borderBottom: "1px solid rgba(255,255,255,.055)" },
  numeric: { textAlign: "right", fontVariantNumeric: "tabular-nums" },
  breakdown: { display: "grid", gap: "10px" },
  breakdownRow: { display: "grid", gridTemplateColumns: "minmax(0, 1fr) auto", gap: "12px", alignItems: "center" },
  breakdownName: { minWidth: 0, overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap" },
  breakdownCount: { color: "#c4b8ff", fontWeight: 800, fontVariantNumeric: "tabular-nums" },
  notice: { padding: "14px 16px", borderRadius: "14px", marginBottom: "18px", lineHeight: 1.5 },
  error: { background: "rgba(255,91,112,.09)", color: "#ffb1bd" },
  empty: { color: "#858b9e", paddingBlock: "28px", textAlign: "center" },
  privacy: {
    marginTop: "18px",
    padding: "14px 16px",
    borderRadius: "14px",
    border: "1px solid rgba(169,145,255,.18)",
    background: "rgba(169,145,255,.055)",
    color: "#aeb3c4",
    fontSize: "13px",
    lineHeight: 1.55,
  },
  link: { color: "#c4b8ff", textDecoration: "none" },
});
