import * as stylex from "@stylexjs/stylex";

export const discoveryStyles = stylex.create({
  page: {
    width: "min(1120px, calc(100% - 32px))",
    minHeight: "calc(100vh - 150px)",
    marginInline: "auto",
    paddingBlock: "64px 90px",
  },
  heading: {
    display: "flex",
    alignItems: { default: "end", "@media (max-width: 760px)": "start" },
    justifyContent: "space-between",
    flexDirection: { default: "row", "@media (max-width: 760px)": "column" },
    gap: "24px",
    marginBottom: "28px",
  },
  eyebrow: {
    color: "#a991ff",
    fontSize: "12px",
    fontWeight: 800,
    letterSpacing: ".16em",
    marginBottom: "12px",
  },
  title: {
    margin: 0,
    fontSize: "clamp(42px, 6vw, 72px)",
    lineHeight: .96,
    letterSpacing: "-.06em",
  },
  intro: {
    maxWidth: "540px",
    color: "#969caf",
    lineHeight: 1.6,
    margin: 0,
  },
  panel: {
    padding: { default: "22px", "@media (max-width: 620px)": "18px" },
    marginBottom: "22px",
    borderRadius: "22px",
    background: "rgba(255,255,255,.035)",
    border: "1px solid rgba(255,255,255,.09)",
  },
  searchGrid: {
    display: "grid",
    gridTemplateColumns: { default: "minmax(220px, 1.5fr) minmax(150px, .7fr) minmax(150px, .7fr) auto", "@media (max-width: 820px)": "1fr 1fr", "@media (max-width: 540px)": "1fr" },
    gap: "12px",
    alignItems: "end",
  },
  field: {
    display: "grid",
    gap: "7px",
  },
  label: {
    color: "#aeb2c2",
    fontSize: "11px",
    fontWeight: 800,
    letterSpacing: ".08em",
  },
  input: {
    width: "100%",
    minHeight: "46px",
    boxSizing: "border-box",
    paddingInline: "14px",
    borderRadius: "13px",
    border: "1px solid rgba(255,255,255,.12)",
    background: "#0c0e14",
    color: "#fff",
    outline: 0,
  },
  textarea: {
    minHeight: "120px",
    paddingBlock: "12px",
    resize: "vertical",
  },
  button: {
    minHeight: "46px",
    paddingInline: "16px",
    borderRadius: "13px",
    border: "1px solid #f7f7fb",
    background: "#f7f7fb",
    color: "#0a0b10",
    fontWeight: 800,
    cursor: "pointer",
    ":disabled": { opacity: .55, cursor: "default" },
  },
  secondaryButton: {
    background: "rgba(255,255,255,.04)",
    border: "1px solid rgba(255,255,255,.13)",
    color: "#f7f7fb",
  },
  actions: {
    display: "flex",
    flexWrap: "wrap",
    gap: "9px",
    alignItems: "center",
  },
  notice: {
    padding: "11px 13px",
    marginBottom: "18px",
    borderRadius: "12px",
    background: "rgba(169,145,255,.08)",
    border: "1px solid rgba(169,145,255,.16)",
    color: "#c9bcff",
    fontSize: "13px",
  },
  error: {
    background: "rgba(255,90,110,.07)",
    border: "1px solid rgba(255,90,110,.16)",
    color: "#ff9ba8",
  },
  profileGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(280px, 1fr))",
    gap: "14px",
  },
  card: {
    display: "flex",
    flexDirection: "column",
    gap: "15px",
    minWidth: 0,
    padding: "20px",
    borderRadius: "22px",
    background: "rgba(255,255,255,.035)",
    border: "1px solid rgba(255,255,255,.09)",
  },
  cardTop: {
    display: "flex",
    alignItems: "center",
    gap: "13px",
  },
  avatar: {
    flexShrink: 0,
    width: "52px",
    height: "52px",
    display: "grid",
    placeItems: "center",
    objectFit: "cover",
    borderRadius: "17px",
    background: "linear-gradient(135deg, #7b5cff, #f04cff)",
    color: "#fff",
    fontSize: "19px",
    fontWeight: 900,
  },
  identity: {
    minWidth: 0,
    display: "grid",
    gap: "2px",
  },
  name: {
    color: "#fff",
    fontSize: "16px",
    fontWeight: 850,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  handle: {
    color: "#8f95a8",
    fontSize: "13px",
  },
  bio: {
    minHeight: "44px",
    margin: 0,
    color: "#9da3b5",
    lineHeight: 1.5,
    fontSize: "14px",
  },
  tags: {
    display: "flex",
    flexWrap: "wrap",
    gap: "6px",
  },
  tag: {
    padding: "5px 8px",
    borderRadius: "999px",
    background: "rgba(169,145,255,.09)",
    border: "1px solid rgba(169,145,255,.14)",
    color: "#c1b3ff",
    fontSize: "11px",
    fontWeight: 750,
  },
  category: {
    background: "rgba(120,255,176,.07)",
    border: "1px solid rgba(120,255,176,.13)",
    color: "#a7efc0",
  },
  stats: {
    display: "flex",
    gap: "15px",
    color: "#868da1",
    fontSize: "12px",
  },
  statStrong: {
    color: "#f7f7fb",
    fontWeight: 800,
  },
  cardFooter: {
    marginTop: "auto",
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: "10px",
  },
  profileLink: {
    color: "#bcaaff",
    fontSize: "13px",
    fontWeight: 800,
  },
  followingButton: {
    background: "rgba(169,145,255,.08)",
    border: "1px solid rgba(169,145,255,.2)",
    color: "#c9bcff",
  },
  empty: {
    minHeight: "260px",
    display: "grid",
    placeItems: "center",
    textAlign: "center",
    color: "#858c9f",
  },
  socialBar: {
    width: "min(520px, 100%)",
    marginBottom: "14px",
    padding: "12px 14px",
    display: "flex",
    flexWrap: "wrap",
    alignItems: "center",
    justifyContent: "center",
    gap: "12px",
    borderRadius: "16px",
    background: "rgba(255,255,255,.035)",
    border: "1px solid rgba(255,255,255,.08)",
  },
  socialStat: {
    color: "#aeb2c2",
    fontSize: "13px",
  },
  settingsCard: {
    width: "min(680px, 100%)",
    marginInline: "auto",
    padding: { default: "28px", "@media (max-width: 620px)": "20px" },
    borderRadius: "24px",
    background: "rgba(255,255,255,.035)",
    border: "1px solid rgba(255,255,255,.09)",
  },
  settingsTitle: {
    margin: "0 0 8px",
    fontSize: "clamp(34px, 5vw, 54px)",
    letterSpacing: "-.055em",
  },
  settingsCopy: {
    color: "#969caf",
    lineHeight: 1.6,
    marginBottom: "24px",
  },
});
