import * as stylex from "@stylexjs/stylex";

export const editorStyles = stylex.create({
  page: {
    width: "min(1040px, calc(100% - 32px))",
    minHeight: "calc(100vh - 150px)",
    marginInline: "auto",
    paddingBlock: "56px 88px",
  },
  topbar: {
    display: "flex",
    alignItems: { default: "end", "@media (max-width: 700px)": "start" },
    justifyContent: "space-between",
    flexDirection: { default: "row", "@media (max-width: 700px)": "column" },
    gap: "20px",
    marginBottom: "28px",
  },
  eyebrow: {
    color: "#a991ff",
    fontSize: "12px",
    fontWeight: 800,
    letterSpacing: ".16em",
    marginBottom: "10px",
  },
  title: {
    margin: 0,
    fontSize: "clamp(38px, 5vw, 64px)",
    lineHeight: 1,
    letterSpacing: "-.055em",
  },
  copy: {
    color: "#969caf",
    lineHeight: 1.6,
    maxWidth: "620px",
  },
  panel: {
    padding: { default: "28px", "@media (max-width: 620px)": "20px" },
    borderRadius: "24px",
    background: "rgba(255,255,255,.035)",
    border: "1px solid rgba(255,255,255,.09)",
    marginBottom: "16px",
  },
  narrow: {
    width: "min(620px, 100%)",
    marginInline: "auto",
  },
  grid: {
    display: "grid",
    gridTemplateColumns: { default: "1fr 1fr", "@media (max-width: 760px)": "1fr" },
    gap: "16px",
  },
  field: {
    display: "grid",
    gap: "7px",
    marginBottom: "14px",
  },
  label: {
    color: "#aeb2c2",
    fontSize: "12px",
    fontWeight: 800,
    letterSpacing: ".04em",
  },
  optional: {
    color: "#666d81",
    fontSize: "10px",
    fontWeight: 700,
  },
  input: {
    width: "100%",
    minHeight: "46px",
    boxSizing: "border-box",
    borderRadius: "13px",
    paddingInline: "14px",
    border: "1px solid rgba(255,255,255,.12)",
    background: "#0c0e14",
    color: "#fff",
    outline: 0,
  },
  textarea: {
    minHeight: "110px",
    resize: "vertical",
    paddingBlock: "12px",
  },
  button: {
    minHeight: "42px",
    borderRadius: "12px",
    paddingInline: "15px",
    border: "1px solid #f7f7fb",
    background: "#f7f7fb",
    color: "#0a0b10",
    fontWeight: 800,
    cursor: "pointer",
    ":disabled": { opacity: .55, cursor: "default" },
  },
  secondary: {
    background: "rgba(255,255,255,.04)",
    color: "#f7f7fb",
    border: "1px solid rgba(255,255,255,.12)",
  },
  danger: {
    background: "rgba(255,90,110,.08)",
    color: "#ff9ba8",
    border: "1px solid rgba(255,90,110,.2)",
  },
  actions: {
    display: "flex",
    flexWrap: "wrap",
    gap: "9px",
    alignItems: "center",
  },
  sectionTitle: {
    margin: "0 0 6px",
    fontSize: "21px",
    letterSpacing: "-.025em",
  },
  sectionCopy: {
    color: "#868da1",
    margin: "0 0 20px",
    fontSize: "14px",
    lineHeight: 1.5,
  },
  linkCard: {
    padding: "18px",
    borderRadius: "18px",
    background: "#0d0f16",
    border: "1px solid rgba(255,255,255,.08)",
    marginTop: "10px",
  },
  linkHeader: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: "12px",
    marginBottom: "12px",
  },
  badge: {
    fontSize: "11px",
    fontWeight: 800,
    padding: "5px 8px",
    borderRadius: "999px",
    background: "rgba(169,145,255,.12)",
    color: "#bcaaff",
  },
  mutedBadge: {
    background: "rgba(255,255,255,.06)",
    color: "#777d91",
  },
  message: {
    padding: "12px 14px",
    marginBottom: "14px",
    borderRadius: "12px",
    background: "rgba(120,255,176,.07)",
    border: "1px solid rgba(120,255,176,.14)",
    color: "#a7efc0",
    fontSize: "13px",
  },
  error: {
    background: "rgba(255,90,110,.07)",
    border: "1px solid rgba(255,90,110,.16)",
    color: "#ff9ba8",
  },
  empty: {
    textAlign: "center",
    paddingBlock: "80px",
  },
  accountRow: {
    display: "flex",
    alignItems: { default: "center", "@media (max-width: 620px)": "start" },
    justifyContent: "space-between",
    flexDirection: { default: "row", "@media (max-width: 620px)": "column" },
    gap: "14px",
    paddingBlock: "15px",
    borderBottom: "1px solid rgba(255,255,255,.07)",
  },
  value: {
    color: "#fff",
    fontWeight: 700,
  },
});
