import * as stylex from "@stylexjs/stylex";

export const feedStyles = stylex.create({
  page: {
    width: "min(1080px, calc(100% - 32px))",
    minHeight: "calc(100vh - 150px)",
    marginInline: "auto",
    paddingBlock: "64px 90px",
  },
  heading: {
    display: "flex",
    alignItems: { default: "end", "@media (max-width: 720px)": "start" },
    justifyContent: "space-between",
    flexDirection: { default: "row", "@media (max-width: 720px)": "column" },
    gap: "22px",
    marginBottom: "26px",
  },
  eyebrow: {
    color: "#a991ff",
    fontSize: "12px",
    fontWeight: 800,
    letterSpacing: ".16em",
    marginBottom: "10px",
  },
  title: {
    margin: 0,
    fontSize: "clamp(42px, 6vw, 72px)",
    lineHeight: .96,
    letterSpacing: "-.06em",
  },
  intro: {
    maxWidth: "500px",
    margin: 0,
    color: "#969caf",
    lineHeight: 1.6,
  },
  layout: {
    display: "grid",
    gridTemplateColumns: { default: "minmax(0, 1fr) 310px", "@media (max-width: 840px)": "1fr" },
    gap: "18px",
    alignItems: "start",
  },
  panel: {
    padding: "20px",
    borderRadius: "22px",
    background: "rgba(255,255,255,.035)",
    border: "1px solid rgba(255,255,255,.09)",
  },
  tabs: {
    display: "flex",
    gap: "8px",
    marginBottom: "16px",
  },
  button: {
    minHeight: "40px",
    paddingInline: "14px",
    borderRadius: "12px",
    background: "rgba(255,255,255,.04)",
    border: "1px solid rgba(255,255,255,.11)",
    color: "#aeb2c2",
    fontWeight: 800,
    cursor: "pointer",
    ":disabled": { opacity: .55, cursor: "default" },
  },
  activeButton: {
    background: "#f7f7fb",
    border: "1px solid #f7f7fb",
    color: "#0a0b10",
  },
  event: {
    display: "grid",
    gridTemplateColumns: "48px minmax(0, 1fr)",
    gap: "13px",
    paddingBlock: "16px",
    borderBottom: "1px solid rgba(255,255,255,.07)",
  },
  avatar: {
    width: "48px",
    height: "48px",
    display: "grid",
    placeItems: "center",
    objectFit: "cover",
    borderRadius: "15px",
    background: "linear-gradient(135deg, #7b5cff, #f04cff)",
    fontWeight: 900,
  },
  eventCopy: {
    minWidth: 0,
    display: "grid",
    gap: "5px",
  },
  eventText: {
    margin: 0,
    color: "#c5c9d6",
    lineHeight: 1.5,
  },
  creator: {
    color: "#fff",
    fontWeight: 850,
  },
  label: {
    color: "#c2b4ff",
    fontWeight: 800,
  },
  time: {
    color: "#73798c",
    fontSize: "12px",
  },
  loadMore: {
    width: "100%",
    marginTop: "16px",
  },
  empty: {
    paddingBlock: "58px",
    textAlign: "center",
    color: "#858c9f",
  },
  notice: {
    padding: "12px 14px",
    marginBottom: "14px",
    borderRadius: "12px",
    background: "rgba(169,145,255,.08)",
    border: "1px solid rgba(169,145,255,.16)",
    color: "#c9bcff",
    fontSize: "13px",
  },
  error: {
    background: "rgba(255,90,110,.07)",
    border: "1px solid rgba(255,90,110,.16)",
    color: "#ff9ba8",
  },
  sideTitle: {
    margin: "0 0 6px",
    fontSize: "18px",
    letterSpacing: "-.025em",
  },
  sideCopy: {
    margin: "0 0 14px",
    color: "#858c9f",
    fontSize: "12px",
    lineHeight: 1.5,
  },
  trend: {
    display: "grid",
    gridTemplateColumns: "32px minmax(0, 1fr) auto",
    alignItems: "center",
    gap: "10px",
    paddingBlock: "11px",
    borderBottom: "1px solid rgba(255,255,255,.06)",
  },
  rank: {
    color: "#777d91",
    fontSize: "12px",
    fontWeight: 800,
  },
  trendIdentity: {
    minWidth: 0,
    display: "grid",
    gap: "2px",
  },
  trendName: {
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    color: "#f7f7fb",
    fontSize: "13px",
    fontWeight: 800,
  },
  trendMeta: {
    color: "#777d91",
    fontSize: "11px",
  },
  score: {
    color: "#bcaaff",
    fontSize: "12px",
    fontWeight: 800,
  },
});
