import * as stylex from "@stylexjs/stylex";

export const growthStyles = stylex.create({
  page: {
    width: "min(1100px, calc(100% - 32px))",
    marginInline: "auto",
    paddingBlock: "64px 96px",
  },
  heading: {
    display: "flex",
    justifyContent: "space-between",
    gap: "24px",
    alignItems: "end",
    marginBottom: "28px",
    flexWrap: "wrap",
  },
  eyebrow: {
    color: "#a991ff",
    fontSize: "12px",
    fontWeight: 800,
    letterSpacing: ".16em",
    marginBottom: "10px",
  },
  title: {
    margin: 0,
    fontSize: "clamp(38px, 5vw, 62px)",
    lineHeight: 1,
    letterSpacing: "-.055em",
  },
  intro: {
    color: "#9aa0b4",
    lineHeight: 1.6,
    maxWidth: "660px",
  },
  grid: {
    display: "grid",
    gridTemplateColumns: { default: "repeat(2, minmax(0, 1fr))", "@media (max-width: 820px)": "1fr" },
    gap: "16px",
  },
  panel: {
    border: "1px solid rgba(255,255,255,.1)",
    background: "rgba(255,255,255,.035)",
    borderRadius: "22px",
    padding: "22px",
  },
  wide: { gridColumn: { default: "1 / -1", "@media (max-width: 820px)": "auto" } },
  panelTitle: { margin: "0 0 8px", fontSize: "20px" },
  help: { color: "#858b9e", lineHeight: 1.5, fontSize: "14px" },
  form: { display: "grid", gap: "12px", marginTop: "16px" },
  row: {
    display: "grid",
    gridTemplateColumns: { default: "repeat(3, minmax(0, 1fr))", "@media (max-width: 680px)": "1fr" },
    gap: "10px",
  },
  field: { display: "grid", gap: "6px" },
  label: { fontSize: "12px", fontWeight: 800, letterSpacing: ".08em", color: "#b6bbca" },
  input: {
    minHeight: "46px",
    borderRadius: "13px",
    border: "1px solid rgba(255,255,255,.12)",
    background: "#0c0e14",
    color: "#fff",
    paddingInline: "14px",
  },
  textarea: {
    minHeight: "100px",
    resize: "vertical",
    borderRadius: "13px",
    border: "1px solid rgba(255,255,255,.12)",
    background: "#0c0e14",
    color: "#fff",
    padding: "12px 14px",
  },
  button: {
    minHeight: "42px",
    borderRadius: "12px",
    border: "1px solid #f7f7fb",
    background: "#f7f7fb",
    color: "#0a0b10",
    fontWeight: 800,
    paddingInline: "15px",
    cursor: "pointer",
  },
  secondaryButton: {
    background: "rgba(255,255,255,.04)",
    color: "#f7f7fb",
    borderColor: "rgba(255,255,255,.12)",
  },
  actions: { display: "flex", flexWrap: "wrap", gap: "9px", marginTop: "12px" },
  generated: {
    display: "block",
    wordBreak: "break-all",
    padding: "12px 14px",
    borderRadius: "13px",
    background: "#0c0e14",
    border: "1px solid rgba(255,255,255,.09)",
    color: "#d9ccff",
    fontFamily: "ui-monospace, SFMono-Regular, Menlo, monospace",
    fontSize: "13px",
  },
  checkRow: { display: "flex", gap: "10px", alignItems: "start" },
  checkbox: { width: "20px", height: "20px", accentColor: "#a991ff" },
  contacts: { display: "grid", gap: "8px", marginTop: "14px" },
  contact: {
    display: "grid",
    gridTemplateColumns: { default: "1fr auto auto", "@media (max-width: 680px)": "1fr" },
    gap: "12px",
    alignItems: "center",
    padding: "12px 14px",
    borderRadius: "14px",
    border: "1px solid rgba(255,255,255,.08)",
  },
  muted: { color: "#858b9e", fontSize: "13px" },
  notice: { marginBlock: "14px", padding: "12px 14px", borderRadius: "12px", fontSize: "14px" },
  success: { background: "rgba(95,211,156,.09)", color: "#a7e6c8" },
  error: { background: "rgba(255,91,112,.09)", color: "#ffb1bd" },
  contactCapture: {
    width: "min(640px, 100%)",
    margin: "18px auto 0",
    padding: "20px",
    borderRadius: "20px",
    border: "1px solid rgba(255,255,255,.1)",
    background: "rgba(255,255,255,.035)",
  },
  contactCaptureTitle: { margin: "0 0 6px", fontSize: "20px" },
  honeypot: { position: "absolute", left: "-10000px", width: "1px", height: "1px", overflow: "hidden" },
});
