import * as stylex from "@stylexjs/stylex";

export const linkToolsStyles = stylex.create({
  page: {
    width: "min(1040px, calc(100% - 32px))",
    marginInline: "auto",
    paddingBlock: "56px 88px",
  },
  heading: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: { default: "end", "@media (max-width: 720px)": "start" },
    flexDirection: { default: "row", "@media (max-width: 720px)": "column" },
    gap: "18px",
    marginBottom: "28px",
  },
  eyebrow: {
    color: "#a991ff",
    fontSize: "12px",
    fontWeight: 800,
    letterSpacing: ".16em",
    marginBottom: "10px",
  },
  title: {
    margin: 0,
    fontSize: "clamp(36px, 5vw, 58px)",
    lineHeight: 1,
    letterSpacing: "-.05em",
  },
  copy: {
    color: "#969caf",
    lineHeight: 1.6,
    maxWidth: "680px",
  },
  workspace: {
    display: "grid",
    gridTemplateColumns: { default: "minmax(0, 1fr) 320px", "@media (max-width: 880px)": "1fr" },
    gap: "18px",
    alignItems: "start",
  },
  panel: {
    padding: { default: "26px", "@media (max-width: 620px)": "18px" },
    borderRadius: "24px",
    background: "rgba(255,255,255,.035)",
    border: "1px solid rgba(255,255,255,.09)",
    marginBottom: "16px",
  },
  stickyPanel: {
    position: { default: "sticky", "@media (max-width: 880px)": "static" },
    top: "20px",
  },
  sectionTitle: {
    margin: "0 0 6px",
    fontSize: "21px",
    letterSpacing: "-.025em",
  },
  sectionCopy: {
    color: "#868da1",
    margin: "0 0 18px",
    fontSize: "14px",
    lineHeight: 1.5,
  },
  field: {
    display: "grid",
    gap: "7px",
    marginBottom: "14px",
  },
  label: {
    color: "#aeb2c2",
    fontSize: "12px",
    fontWeight: 800,
    letterSpacing: ".04em",
  },
  input: {
    width: "100%",
    minHeight: "44px",
    boxSizing: "border-box",
    borderRadius: "12px",
    paddingInline: "13px",
    border: "1px solid rgba(255,255,255,.12)",
    background: "#0c0e14",
    color: "#fff",
    outline: 0,
  },
  textarea: {
    minHeight: "190px",
    resize: "vertical",
    padding: "12px 13px",
    lineHeight: 1.45,
  },
  row: {
    padding: "16px",
    marginTop: "10px",
    borderRadius: "17px",
    background: "#0d0f16",
    border: "1px solid rgba(255,255,255,.08)",
  },
  rowHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    gap: "12px",
    marginBottom: "12px",
  },
  grid: {
    display: "grid",
    gridTemplateColumns: { default: "1fr 1fr", "@media (max-width: 680px)": "1fr" },
    gap: "12px",
  },
  actions: {
    display: "flex",
    flexWrap: "wrap",
    alignItems: "center",
    gap: "9px",
  },
  button: {
    minHeight: "42px",
    borderRadius: "12px",
    paddingInline: "15px",
    border: "1px solid #f7f7fb",
    background: "#f7f7fb",
    color: "#0a0b10",
    fontWeight: 800,
    cursor: "pointer",
    ":disabled": { opacity: .55, cursor: "default" },
  },
  secondary: {
    background: "rgba(255,255,255,.04)",
    color: "#f7f7fb",
    border: "1px solid rgba(255,255,255,.12)",
  },
  note: {
    margin: "8px 0 0",
    color: "#aeb2c2",
    fontSize: "12px",
    lineHeight: 1.45,
  },
  message: {
    padding: "12px 14px",
    marginBottom: "14px",
    borderRadius: "12px",
    background: "rgba(120,255,176,.07)",
    border: "1px solid rgba(120,255,176,.14)",
    color: "#a7efc0",
    fontSize: "13px",
  },
  error: {
    background: "rgba(255,90,110,.07)",
    border: "1px solid rgba(255,90,110,.16)",
    color: "#ff9ba8",
  },
  errors: {
    color: "#ff9ba8",
    fontSize: "13px",
    lineHeight: 1.5,
    paddingLeft: "20px",
  },
  qr: {
    width: "min(220px, 100%)",
    height: "auto",
    aspectRatio: "1 / 1",
    display: "block",
    margin: "16px auto",
    borderRadius: "18px",
    background: "#fff",
  },
  canonical: {
    wordBreak: "break-all",
    color: "#d8d9e2",
    fontSize: "13px",
    lineHeight: 1.5,
  },
  empty: {
    textAlign: "center",
    paddingBlock: "90px",
  },
});
