import * as stylex from "@stylexjs/stylex";

export const profileEditorPanelStyles = stylex.create({
  workspace: {
    display: "grid",
    gridTemplateColumns: { default: "minmax(0, 1fr) minmax(300px, 390px)", "@media (max-width: 900px)": "1fr" },
    gap: "18px",
    alignItems: "start",
    marginBottom: "18px",
  },
  panel: {
    padding: { default: "28px", "@media (max-width: 620px)": "20px" },
    borderRadius: "24px",
    background: "rgba(255,255,255,.035)",
    border: "1px solid rgba(255,255,255,.09)",
  },
  title: { margin: "0 0 6px", fontSize: "21px", letterSpacing: "-.025em" },
  copy: { color: "#868da1", margin: "0 0 20px", fontSize: "14px", lineHeight: 1.5 },
  field: { display: "grid", gap: "7px", marginBottom: "14px" },
  label: { color: "#aeb2c2", fontSize: "12px", fontWeight: 800, letterSpacing: ".04em" },
  optional: { color: "#666d81", fontSize: "10px", fontWeight: 700 },
  input: {
    width: "100%",
    minHeight: "46px",
    boxSizing: "border-box",
    borderRadius: "13px",
    paddingInline: "14px",
    border: "1px solid rgba(255,255,255,.12)",
    background: "#0c0e14",
    color: "#fff",
    outline: 0,
  },
  textarea: { minHeight: "110px", resize: "vertical", paddingBlock: "12px" },
  mediaBox: {
    padding: "14px",
    marginBottom: "14px",
    borderRadius: "15px",
    display: "grid",
    gap: "11px",
    background: "rgba(255,255,255,.025)",
    border: "1px solid rgba(255,255,255,.08)",
  },
  mediaHelp: {
    margin: "5px 0 0",
    color: "#777f93",
    fontSize: "12px",
    lineHeight: 1.45,
  },
  mediaActions: {
    display: "flex",
    flexWrap: "wrap",
    gap: "8px",
  },
  uploadButton: {
    minHeight: "38px",
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    paddingInline: "13px",
    borderRadius: "11px",
    border: "1px solid #f7f7fb",
    background: "#f7f7fb",
    color: "#0a0b10",
    fontSize: "12px",
    fontWeight: 800,
    cursor: "pointer",
  },
  secondaryButton: {
    minHeight: "38px",
    paddingInline: "13px",
    borderRadius: "11px",
    border: "1px solid rgba(255,255,255,.12)",
    background: "rgba(255,255,255,.04)",
    color: "#f7f7fb",
    fontSize: "12px",
    fontWeight: 800,
    cursor: "pointer",
    ":disabled": { opacity: .45, cursor: "default" },
  },
  disabledButton: { opacity: .45, cursor: "default" },
  fileInput: {
    position: "absolute",
    width: "1px",
    height: "1px",
    padding: 0,
    margin: "-1px",
    overflow: "hidden",
    clip: "rect(0, 0, 0, 0)",
    whiteSpace: "nowrap",
    border: 0,
  },
  mediaMessage: {
    color: "#a7efc0",
    fontSize: "12px",
    lineHeight: 1.4,
  },
  mediaError: {
    color: "#ff9ba8",
    fontSize: "12px",
    lineHeight: 1.4,
  },
  themes: {
    display: "grid",
    gridTemplateColumns: "repeat(2, minmax(0, 1fr))",
    gap: "8px",
    marginBottom: "18px",
  },
  theme: {
    minHeight: "76px",
    padding: "11px",
    borderRadius: "14px",
    display: "grid",
    gap: "4px",
    textAlign: "left",
    background: "rgba(255,255,255,.03)",
    border: "1px solid rgba(255,255,255,.1)",
    color: "#e9eaf1",
    cursor: "pointer",
  },
  themeSelected: {
    border: "1px solid #aa91ff",
    background: "rgba(169,145,255,.1)",
    boxShadow: "0 0 0 1px rgba(169,145,255,.16)",
  },
  themeName: { fontWeight: 850, fontSize: "13px" },
  themeDescription: { color: "#858ca0", fontSize: "11px", lineHeight: 1.35 },
  button: {
    minHeight: "42px",
    borderRadius: "12px",
    paddingInline: "15px",
    border: "1px solid #f7f7fb",
    background: "#f7f7fb",
    color: "#0a0b10",
    fontWeight: 800,
    cursor: "pointer",
    ":disabled": { opacity: .55, cursor: "default" },
  },
  previewColumn: {
    position: { default: "sticky", "@media (max-width: 900px)": "static" },
    top: "20px",
    padding: "10px",
    borderRadius: "30px",
    border: "1px solid rgba(255,255,255,.1)",
    background: "rgba(255,255,255,.025)",
  },
  previewLabel: {
    padding: "7px 8px 12px",
    color: "#777d91",
    fontSize: "11px",
    fontWeight: 800,
    letterSpacing: ".1em",
  },
});
