import * as stylex from "@stylexjs/stylex";

export const styles = stylex.create({
  app: {
    minHeight: "100vh",
    color: "#f7f7fb",
  },
  header: {
    width: "min(1180px, calc(100% - 32px))",
    marginInline: "auto",
    minHeight: "76px",
    display: "flex",
    alignItems: "center",
    gap: "28px",
    borderBottom: "1px solid rgba(255,255,255,.08)",
  },
  brand: {
    display: "flex",
    alignItems: "center",
    gap: "10px",
    fontWeight: 800,
    letterSpacing: "-0.04em",
    fontSize: "20px",
  },
  brandMark: {
    width: "34px",
    height: "34px",
    display: "grid",
    placeItems: "center",
    borderRadius: "11px",
    background: "linear-gradient(135deg, #7b5cff, #f04cff)",
    boxShadow: "0 0 28px rgba(123,92,255,.45)",
    fontSize: "13px",
    letterSpacing: "-0.03em",
  },
  nav: {
    display: "flex",
    alignItems: "center",
    gap: "20px",
    marginRight: "auto",
  },
  navLink: {
    color: "#aeb2c2",
    fontSize: "14px",
    transition: "color 160ms ease",
    ":hover": { color: "#ffffff" },
  },
  hero: {
    width: "min(1180px, calc(100% - 32px))",
    marginInline: "auto",
    minHeight: "calc(100vh - 150px)",
    display: "grid",
    gridTemplateColumns: { default: "minmax(0, 1.05fr) minmax(320px, .75fr)", "@media (max-width: 800px)": "1fr" },
    alignItems: "center",
    gap: { default: "72px", "@media (max-width: 800px)": "44px" },
    paddingBlock: { default: "72px 96px", "@media (max-width: 800px)": "48px 72px" },
  },
  heroCopy: { maxWidth: "710px" },
  eyebrow: {
    color: "#a991ff",
    fontSize: "12px",
    fontWeight: 800,
    letterSpacing: ".16em",
    marginBottom: "14px",
  },
  heroTitle: {
    margin: 0,
    fontSize: "clamp(52px, 7vw, 96px)",
    lineHeight: ".92",
    letterSpacing: "-.075em",
    maxWidth: "850px",
  },
  accent: {
    color: "#c4b6ff",
  },
  heroBody: {
    maxWidth: "650px",
    color: "#aeb2c2",
    fontSize: "clamp(18px, 2vw, 22px)",
    lineHeight: 1.55,
    marginBlock: "28px 0",
  },
  actions: {
    display: "flex",
    flexWrap: "wrap",
    gap: "12px",
    marginTop: "30px",
  },
  primaryButton: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    minHeight: "48px",
    paddingInline: "20px",
    borderRadius: "15px",
    background: "#f7f7fb",
    color: "#0a0b10",
    fontWeight: 800,
    border: "1px solid #f7f7fb",
    boxShadow: "0 10px 28px rgba(0,0,0,.22)",
  },
  secondaryButton: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    minHeight: "48px",
    paddingInline: "20px",
    borderRadius: "15px",
    background: "rgba(255,255,255,.04)",
    color: "#f7f7fb",
    fontWeight: 700,
    border: "1px solid rgba(255,255,255,.12)",
  },
  smallButton: {
    minHeight: "38px",
    paddingInline: "14px",
    borderRadius: "12px",
    fontSize: "13px",
    display: { default: "inline-flex", "@media (max-width: 640px)": "none" },
  },
  fullButton: { width: "100%", marginTop: "14px" },
  domainNote: {
    marginTop: "28px",
    color: "#777d91",
    fontSize: "13px",
  },
  heroPreview: {
    border: "1px solid rgba(255,255,255,.12)",
    borderRadius: "30px",
    padding: "10px",
    background: "rgba(255,255,255,.035)",
    boxShadow: "0 40px 100px rgba(0,0,0,.35), 0 0 80px rgba(123,92,255,.12)",
  },
  previewChrome: {
    minHeight: "42px",
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    paddingInline: "14px",
    color: "#777d91",
    fontSize: "12px",
  },
  previewCard: {
    minHeight: "510px",
    borderRadius: "23px",
    padding: "44px 30px",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    background: "linear-gradient(160deg, #151925 0%, #0d0f16 58%, #171126 100%)",
    border: "1px solid rgba(255,255,255,.08)",
  },
  avatar: {
    width: "78px",
    height: "78px",
    display: "grid",
    placeItems: "center",
    borderRadius: "26px",
    background: "linear-gradient(135deg, #7b5cff, #f04cff)",
    fontSize: "28px",
    fontWeight: 900,
    boxShadow: "0 16px 44px rgba(123,92,255,.28)",
  },
  smallAvatar: { width: "48px", height: "48px", borderRadius: "16px", fontSize: "18px" },
  profileAvatar: { width: "96px", height: "96px", borderRadius: "30px", fontSize: "34px" },
  previewName: { marginTop: "18px", fontSize: "20px" },
  muted: { color: "#8f95a8", lineHeight: 1.5 },
  previewLink: {
    width: "100%",
    minHeight: "58px",
    marginTop: "12px",
    paddingInline: "18px",
    borderRadius: "18px",
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    background: "rgba(255,255,255,.055)",
    border: "1px solid rgba(255,255,255,.08)",
    fontWeight: 700,
  },
  section: {
    width: "min(1060px, calc(100% - 32px))",
    minHeight: "calc(100vh - 150px)",
    marginInline: "auto",
    paddingBlock: "70px 90px",
  },
  sectionHeading: {
    display: "flex",
    justifyContent: "space-between",
    gap: "24px",
    marginBottom: "34px",
    alignItems: { default: "end", "@media (max-width: 720px)": "start" },
    flexDirection: { default: "row", "@media (max-width: 720px)": "column" },
  },
  sectionTitle: {
    margin: 0,
    fontSize: "clamp(38px, 5vw, 68px)",
    lineHeight: 1,
    letterSpacing: "-.06em",
  },
  sectionIntro: {
    color: "#8f95a8",
    maxWidth: "520px",
    lineHeight: 1.55,
  },
  profileGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(260px, 1fr))",
    gap: "14px",
  },
  discoveryCard: {
    padding: "22px",
    borderRadius: "22px",
    background: "rgba(255,255,255,.035)",
    border: "1px solid rgba(255,255,255,.09)",
  },
  cardMeta: { color: "#b7a8ff", fontSize: "13px", fontWeight: 700 },
  createSection: { display: "grid", placeItems: "center" },
  createCard: {
    width: "min(600px, 100%)",
    padding: "34px",
    borderRadius: "28px",
    background: "rgba(255,255,255,.04)",
    border: "1px solid rgba(255,255,255,.1)",
  },
  inputLabel: {
    display: "block",
    marginBlock: "24px 8px",
    color: "#aeb2c2",
    fontSize: "13px",
    fontWeight: 700,
  },
  handleInput: {
    display: "flex",
    alignItems: "center",
    minHeight: "58px",
    gap: "2px",
    paddingInline: "16px",
    borderRadius: "16px",
    background: "#0c0e14",
    border: "1px solid rgba(255,255,255,.12)",
    color: "#777d91",
    fontWeight: 700,
  },
  textInput: {
    minWidth: 0,
    flex: 1,
    border: 0,
    outline: 0,
    color: "#fff",
    background: "transparent",
  },
  profilePage: {
    minHeight: "calc(100vh - 150px)",
    display: "grid",
    placeItems: "center",
    padding: "50px 16px 80px",
  },
  publicProfile: {
    width: "min(520px, 100%)",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    textAlign: "center",
    padding: "38px 28px",
  },
  profileTitle: { margin: "18px 0 0", fontSize: "32px", letterSpacing: "-.04em" },
  profileBio: { maxWidth: "390px", color: "#aeb2c2", lineHeight: 1.55 },
  linkStack: { width: "100%", display: "grid", gap: "12px", marginTop: "22px" },
  publicLink: {
    minHeight: "64px",
    paddingInline: "19px",
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    borderRadius: "20px",
    background: "rgba(255,255,255,.055)",
    border: "1px solid rgba(255,255,255,.1)",
    fontWeight: 800,
  },
  vutameBadge: {
    marginTop: "28px",
    color: "#777d91",
    fontSize: "12px",
    fontWeight: 700,
  },
  emptyState: {
    minHeight: "calc(100vh - 150px)",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    textAlign: "center",
    gap: "10px",
    padding: "40px 16px",
    color: "#aeb2c2",
  },
  footer: {
    width: "min(1180px, calc(100% - 32px))",
    minHeight: "74px",
    marginInline: "auto",
    borderTop: "1px solid rgba(255,255,255,.08)",
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: "20px",
    color: "#666c7e",
    fontSize: "12px",
  },
});
